name: TestRPG
version: 0.0.1
main: me.Vark123.TestRPG.TestRPG
author: Vark123
load: POSTWORLD
depend: [Citizens]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.3

commands:
  rpg: